# Example ingress yaml with annotations.
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    # Set to internal or internet-facing, so feed-dns will point to the correct endpoint.
    sky.uk/frontend-scheme: internal

    # Specify the feed-ingress controller that should adopt this ingress
    sky.uk/ingress-controller-name: main

    # nginx allow clause for this ingress.
    sky.uk/allow: 10.10.82.0/24

    # Strip the path from the path passed to the backend service.
    sky.uk/strip-path: "true"

    # Max timeout for requests. Values must be quoted or they'll be silently dropped by kubectl.
    sky.uk/backend-timeout-seconds: "20"

    # Maximum backend connections (http://nginx.org/en/docs/http/ngx_http_upstream_module.html#max_conns). Values must be quoted or they'll be silently dropped by kubectl.
    sky.uk/backend-max-connections: "512"
spec:
  rules:
  - host: example.bskyb.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 8080
        path: /prefix/my-service/
